"""
Django settings for Baseball_django project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s4kubj#0h++4=^gyo$cl2*m1@y_4!r3d%)uvf#vz&hg06(gk7+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.168.89',  # 手机访问的局域网 IP
    '.ngrok-free.dev',   # 允许所有 ngrok 子域名
]
# 允许通过局域网访问时的 CSRF 来源（仅开发）
CSRF_TRUSTED_ORIGINS = [
    'http://192.168.168.89:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    # 添加HTTPS ngrok URL
    'https://quyen-unsanctified-francina.ngrok-free.dev',
    # 为了更通用，也可以添加通配符（推荐）
    'https://*.ngrok-free.dev',
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ckeditor",
    "knowledge",
    "moments",
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "Baseball_django.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Baseball_django.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / 'Photo',  # 添加Photo目录到静态文件查找路径
]

# 定义STATIC_ROOT（用于生产环境）
STATIC_ROOT = BASE_DIR / 'staticfiles'

# CKEditor 配置：允许字体大小与对齐
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': [
            {'name': 'basicstyles', 'items': ['Bold', 'Italic', 'Underline', 'Strike', 'RemoveFormat']},
            {'name': 'paragraph', 'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
            {'name': 'styles', 'items': ['Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'clipboard', 'items': ['Undo', 'Redo']},
            {'name': 'links', 'items': ['Link', 'Unlink']},
            {'name': 'insert', 'items': ['Table', 'HorizontalRule']},
            {'name': 'tools', 'items': ['Maximize']},
        ],
        'extraPlugins': ','.join([
            'justify',  # 对齐
            'font',     # 字体与大小
            'colorbutton',
        ]),
        'removePlugins': 'image,sourcearea',
        'height': 300,
        'width': 'auto',
        # 通过 data: URL 注入极小的样式以减小段落间距（无需额外文件）
        'contentsCss': [
            'data:text/css;charset=utf-8,'
            'html%2Cbody%7Bmargin%3A0%3Bpadding%3A0%7D'
            'body%7Bline-height%3A1.6%3Bfont-family%3A-apple-system%2CBlinkMacSystemFont%2C%22Segoe%20UI%22%2CRoboto%2CHelvetica%2CArial%2C%22Noto%20Sans%22%2C%22PingFang%20SC%22%2C%22Microsoft%20Yahei%22%2Csans-serif%7D'
            'p%7Bmargin%3A0.5rem%200%7D'
            'h1%2Ch2%2Ch3%2Ch4%2Ch5%2Ch6%7Bmargin%3A0.8rem%200%200.4rem%7D'
            'ul%2Col%7Bmargin%3A0.5rem%200%200.5rem%201.25rem%7D'
            'img%7Bmax-width%3A100%25%3Bheight%3Aauto%7D'
            'table%7Bborder-collapse%3Acollapse%7D'
            'table%20td%2Ctable%20th%7Bpadding%3A6px%208px%7D'
        ],
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# 允许所有前端访问（开发阶段）
CORS_ALLOW_ALL_ORIGINS = True

# 添加媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/moments/login/'
LOGOUT_REDIRECT_URL = '/moments/'