# Generated by Django 5.2.6 on 2025-09-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
        migrations.AddField(
            model_name="article",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="article_videos/"),
        ),
    ]
