# Generated by Django 5.2.6 on 2025-09-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_remove_article_image_remove_article_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[("training", "训练"), ("rules", "规则")],
                default="training",
                max_length=20,
            ),
        ),
    ]
