# Generated by Django 5.2.6 on 2025-10-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "knowledge",
            "0005_articleimage_uploaded_at_articlevideo_uploaded_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlevideo",
            name="article",
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
        migrations.AddField(
            model_name="article",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="article_videos/"),
        ),
        migrations.DeleteModel(
            name="ArticleImage",
        ),
        migrations.DeleteModel(
            name="ArticleVideo",
        ),
    ]
