# Generated by Django 5.2.7 on 2025-10-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "knowledge",
            "0005_articleimage_uploaded_at_articlevideo_uploaded_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[("training", "训练"), ("rules", "规则"), ("other", "其他")],
                default="training",
                max_length=100,
            ),
        ),
    ]
