# Generated by Django 5.2.6 on 2025-09-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moment",
            options={},
        ),
        migrations.RemoveField(
            model_name="moment",
            name="image",
        ),
        migrations.CreateModel(
            name="MomentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="moment_images/", verbose_name="图片"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "moment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="moments.moment",
                        verbose_name="时刻",
                    ),
                ),
            ],
            options={
                "verbose_name": "我的时刻",
                "verbose_name_plural": "我的时刻",
                "ordering": ["-created_at"],
            },
        ),
    ]
