# Generated by Django 5.2.6 on 2025-09-29 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0002_alter_moment_options_remove_moment_image_momentimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="momentimage",
            options={},
        ),
        migrations.AlterField(
            model_name="momentimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="momentimage",
            name="image",
            field=models.ImageField(upload_to="moment_images/"),
        ),
        migrations.AlterField(
            model_name="momentimage",
            name="moment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="moments.moment",
            ),
        ),
    ]
