# Generated by Django 5.2.6 on 2025-10-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0003_alter_momentimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moment",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
